events {
    worker_connections 1024;
}

http {
    # 1. Khai báo cụm Backend (Spring Boot)
    upstream backend_cluster {
        server backend:8080; # Đảm bảo tên 'backend' khớp trong docker-compose.yml
    }

    # 2. Khai báo cụm Frontend (Container chạy React/Vite)
    upstream frontend_cluster {
        server frontend:80; # Tên 'frontend' phải khớp service name trong docker-compose.yml
    }

    server {
        listen 80;
        server_name tlong1312.me www.tlong1312.me; # Khai báo tên miền của ông

	location ~ ^/(login|register) {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Nếu gõ link trên trình duyệt (GET) -> Đẩy về Frontend để lấy giao diện React
            if ($request_method = GET) {
                proxy_pass http://frontend_cluster;
            }
            
            # Nếu bấm nút Đăng nhập/Đăng ký trên Form (POST) -> Đẩy data về Spring Boot
            if ($request_method = POST) {
                proxy_pass http://backend_cluster;
            }
        }

        # 2. Riêng Refresh Token (Chỉ có React gọi ngầm API bằng POST)
        location = /refresh {
            proxy_pass http://backend_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # LUỒNG 1: Khách vào trang web bình thường -> Đẩy sang React Frontend
        location / {
            proxy_pass http://frontend_cluster;
            
            # Mấy cái header này giữ lại để mốt thằng VNPay nó nhận diện đúng IP thật của khách
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # LUỒNG 2: Khách gọi API (thường có /api/ ở đầu) -> Đẩy về Spring Boot
        # Lưu ý: Sửa lại chữ /api/ cho đúng với cái @RequestMapping tổng trong Spring Boot của ông nhé
        location /api/ {
            proxy_pass http://backend_cluster;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Origin $http_origin;
        }
    }
}
