
server.port=8080
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=false
server.servlet.session.timeout=30m

spring.application.name=TourApplication
app.name=Tour Application
app.url=${app.backend.url}
app.backend.url=${APP_BACKEND_URL:http://localhost:8080}
app.frontend.url=${APP_FRONTEND_URL:http://localhost:5173}

spring.main.allow-bean-definition-overriding=true


spring.datasource.url=jdbc:postgresql://${DB_POSTGRES_HOST:localhost}:5432/vector_db
spring.datasource.username=${DB_POSTGRES_USER:postgres}
spring.datasource.password=${DB_POSTGRES_PASSWORD:postgres123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBIT_USER:tour_admin}
spring.rabbitmq.password=${RABBIT_PASS:tour_password}
spring.rabbitmq.listener.simple.acknowledge-mode=manual

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.cache-names=tour_list,categories,tours

spring.ai.openai.api-key=${DEEPSEEK_API_KEY}
spring.ai.openai.chat.base-url=https://api.deepseek.com
spring.ai.openai.chat.options.model=deepseek-chat



spring.ai.openai.embedding.base-url=https://generativelanguage.googleapis.com/v1beta/openai/
spring.ai.openai.embedding.options.model=gemini-embedding-001
spring.ai.openai.embedding.embeddings-path=/embeddings
spring.ai.openai.embedding.options.dimensions=768
gemini.api-key=${GEMINI_API_KEY}


spring.ai.chat.memory.repository.jdbc.initialize-schema=always


spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.remove-existing-vector-store-table=false
spring.ai.vectorstore.pgvector.initialize-schema=true


logging.level.root=INFO
logging.level.com.longne.tourapplication=DEBUG
logging.level.org.springframework.ai=DEBUG
logging.level.org.hibernate.SQL=DEBUG


spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.jackson.default-property-inclusion=non_null

spring.security.oauth2.client.registration.google.client-id=761752027345-vgpemtbjkiem6hlcc4ufd64hb7pgm4s3.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

logging.level.org.springframework.security=DEBUG


vnpay.tmn-code=${VNPAY_TMN_CODE:FZVQ6PFX}
vnpay.hash-secret=${VNPAY_HASH_SECRET}
vnpay.url= https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=${app.backend.url}/api/bookings/vnpay-return

spring.mail.host=smtp.sendgrid.net
spring.mail.port=2525
spring.mail.username=apikey
spring.mail.password=${SENDGRID_API_KEY}
app.email.from=dangtieulong204@gmail.com
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=dangtieulong204@gmail.com
#spring.mail.password=gzvw vrgl ldzz wvcx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true

